<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>CQL</string>
    <key>scopeName</key>
    <string>source.cql</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#comments</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#strings</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#constants</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#keywords</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#types</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functions</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#operators</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#identifiers</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.line.double-slash.cql</string>
            <key>match</key>
            <string>(//|--).*</string>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.cql</string>
            <key>begin</key>
            <string>/\*</string>
            <key>end</key>
            <string>\*/</string>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.single.cql</string>
            <key>match</key>
            <string>'(?:[^'\\]|\\.)*'</string>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.double.cql</string>
            <key>match</key>
            <string>"(?:[^"\\]|\\.)*"</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.language.boolean.cql</string>
            <key>match</key>
            <string>\b(true|false)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.uuid.cql</string>
            <key>match</key>
            <string>\b[0-9a-fA-F]{8}(-[0-9a-fA-F]{4}){3}-[0-9a-fA-F]{12}\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.float.cql</string>
            <key>match</key>
            <string>-?\d+\.\d+([eE][+-]?\d+)?</string>
          </dict>
          <dict>
            <key>name</key>
            <string>constant.numeric.integer.cql</string>
            <key>match</key>
            <string>\b-?\d+\b</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.cql</string>
            <key>match</key>
            <string>\b(SELECT|INSERT|COMPACTION|UPDATE|EDGE|LABEL|DELETE|RENAME|CREATE|DROP|ALTER|TRUNCATE|USE|BEGIN|BATCH|APPLY|FROM|INTO|WHERE|SET|IF|AND|OR|NOT|EXISTS|WITH|ORDER|BY|LIMIT|USING|ALLOW|FILTERING|PRIMARY|KEY|IF|NOT|EXISTS|ADD|TO)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.cql</string>
            <key>match</key>
            <string>\b(KEYSPACE|TABLE|COLUMN|TYPE|USER|ROLE|PERMISSION|INDEX|MATERIALIZED|VIEW|FUNCTION|AGGREGATE)\b</string>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.cql</string>
            <key>match</key>
            <string>\b(ASCII|BIGINT|BLOB|BOOLEAN|COUNTER|DATE|DECIMAL|DOUBLE|FLOAT|FROZEN|INET|INT|LIST|MAP|SET|SMALLINT|TEXT|TIME|TIMESTAMP|TIMEUUID|TINYINT|TUPLE|UUID|VARCHAR|VARINT|graph_engine)\b</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>support.function.cql</string>
            <key>match</key>
            <string>\b(count|max|min|sum|avg|token|writetime|ttl)\b</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.comparison.cql</string>
            <key>match</key>
            <string>(=|&gt;|&lt;|&gt;=|&lt;=|!=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.cql</string>
            <key>match</key>
            <string>(\+=|-=|\*=|/=|%=|=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.cql</string>
            <key>match</key>
            <string>(\+|\-|\*|/|%)</string>
          </dict>
        </array>
      </dict>
      <key>identifiers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.other.outline.cql</string>
            <key>match</key>
            <string>@[A-Za-z_][\w-]*</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>